Resources:
  VoterGroupsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}
      AttributeDefinitions:
      - AttributeName: voterGroupId
        AttributeType: S
      - AttributeName: userId
        AttributeType: S
      KeySchema:
      - AttributeName: voterGroupId
        KeyType: HASH
      - AttributeName: userId
        KeyType: RANGE
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
      GlobalSecondaryIndexes:
      - IndexName: userVoterGroupIdx
        KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: voterGroupId
          KeyType: RANGE

        Projection:
          ProjectionType: ALL
        # Set the capacity based on the stage
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.tableThroughput}
          WriteCapacityUnits: ${self:custom.tableThroughput}
