Resources:
  Votes:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}
      AttributeDefinitions:
      - AttributeName: voteId
        AttributeType: S
      - AttributeName: proposalId
        AttributeType: S
      KeySchema:
      - AttributeName: voteId
        KeyType: HASH
      - AttributeName: proposalId
        KeyType: RANGE
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
      GlobalSecondaryIndexes:
      - IndexName: proposalVoteIdx
        KeySchema:
        - AttributeName: proposalId
          KeyType: HASH
        - AttributeName: voteId
          KeyType: RANGE

        Projection:
          ProjectionType: ALL
        # Set the capacity based on the stage
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.tableThroughput}
          WriteCapacityUnits: ${self:custom.tableThroughput}
